sudo: required

services:
    - docker

language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=lint

script:
  - ./ci/run_tests.sh ${TOXENV}
