version: '2'
services:
  master:
    image: python:3.6.2-alpine
    command: sh -c "cd /financier; pip install -r requirements.txt; python app.py"
    env_file: .env
    working_dir: /financier
    ports:
      - 5000:5000
    volumes:
      - .:/financier

