version: '2'
services:
  flask_app:
    build:
      context: '.'
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./budget_builder:/financier/budget_builder
      - ./financier_flask:/financier/financier_flask

